### ISSUE TITLE
Displayed buttons do not match config

### ISSUE THREAD

**Issue by TheRealMarnes** [benbasson/imagetoolbar#11]
This is a problem I've been having for months in an up-to-date Firefox.

Config: http://i.imgur.com/WnLdDaS.png
Actual result: http://i.imgur.com/iozYkXT.png

Link for reference: http://cheezburger.com/8489879040/funny-memes-you-really-think-i-want-be-here

At random times (and rather often), the buttons displayed on the toolbar aren't even close to what's configured. It happens on just about any website, I don't see any kind of pattern or obvious cause. The cases where the bar works 100% as expected are really rare. A reinstall did not help.

Win 8.1, always latest stable FF

**Comment by TheRealMarnes** [comment]
Funnily enough, after closing the affected tab and then opening the link I included to go back to the same page, it did work as expected: http://i.imgur.com/nkf3zOZ.png

**Comment by gmoises** [comment]
I have the same problem, I tried both of your links;
In the first link's image, the toolbar works as expected (small icons, no labels)
In the second link's image, the toolbar shows big icons and double row of labels.

**Comment by TheRealMarnes** [comment]
@gmoises I've actually started making my own addon now... It'll only have the Download functionality but that's fine for my case. I'm making it restartless and as minimal/lightweight as possible as with all my addons... So for me at least this bug is no longer relevant, but @benbasson should still fix it of course :)

**Comment by benbasson** [comment]
I'm guessing this is a Windows 8 thing. I will look into it.

**Comment by benbasson** [comment]
Will be fixed by #24. Probably.
