### ISSUE TITLE
Does not work with firefox beta 43.0 upwards 

### ISSUE THREAD

**Issue by tempmessage** [benbasson/imagetoolbar#17]
Hi Ben 

I absolutely love imagetoolbar! Unfortunately it does not work with firefox beta 43.0 upwards. Instead what happens is it actually ends up completely blocking out all images in firefox.

The last version imagetoolbar works with is firefox 42.0b9.

**Comment by benbasson** [comment]
Thanks for the report, I'll take a look at the weekend and see what I can
do.

**Comment by benbasson** [comment]
Ok, so good news and bad news.
Good news: I can quickly add something to the add-on manifest that'll fix up Image Toolbar for the short term.
Bad news: I'll probably have to completely rewrite Image Toolbar for e10s.

**Comment by bobbomb** [comment]
Hello Ben.
Thank you so much for this extension. 
I can add that the issue seems to be related with the 64 bit version. I Had no problem with the 32 bit version, but since the upgrade no image is showing up on pages.
