### ISSUE TITLE
Sometimes wrong filenames and extensions with Firefox 45.0

### ISSUE THREAD

**Issue by ed81** [benbasson/imagetoolbar#19]
Hello!

First of all I'd like to thank you for creating this addon! I really really love it!  
Since I updated to Firefox 45.0, sometimes pictures are saved with wrong names and extensions, for example "file.htm" or "file.php". This happens mostly on forums, but also on quite normal pages. But when I right-click on the picture and choose "Save as..." it will be saved with the correct name and extension.

Here are two example links where imagetoolbar isn't working properly: 
http://b2b.atv.at/binaries/asset/download_assets/5978535/file

https://forum.digitalfernsehen.de/proxy.php?image=https%3A%2F%2Fscontent-fra3-1.xx.fbcdn.net%2Fhphotos-xtl1%2Fv%2Ft1.0-9%2F12795573_1056705581058127_7585259572724974478_n.png%3Foh%3Df82c17e5ea3849c6b088c842d27fd023%26oe%3D578C46F7&hash=b7447390a57727a6a7c2338f58bcbc78

I hope this helps you to find out what's wrong. Thanks in advance for your effort.

Best wishes from Austria,
Ed

**Comment by yarrmateys** [comment]
this also happens to twitter images, which get a %20large at the end of their extension, and wikia almost always become latest.png now.

**Comment by denisliber** [comment]
Indeed, same behavior here. Mainly on forums presenting images in separate page, the image is saved as 'attachment.php'. Previous versions did not have such a behavior.
http://www.dpreview.com/forums/post/57201691

**Comment by denisliber** [comment]
and how can this be implemented? should we wait for an update?

**Comment by TLoATDaE** [comment]
I'm not sure exactly what's happening inside the code. I just made an observation that it was going on, and hoping that a developer might pick up the ball and run with it.. This is (IMNSHO) a very nice add-on and I would hat to have to get rid of it because the double text labels when there should be none get in my way one time too many.

Let's all hope for an update on this, shall we?
