### ISSUE TITLE
[Bug] Shows wrong description text for icon

### ISSUE THREAD

**Issue by pro100Hub** [benbasson/imagetoolbar#25]
Mozilla Firefox: 51.0.1
Extension: 0.6.18

Example: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=14198
The text for the buttons is OFF in the settings.

I attached screenshot.
Please see: https://s6.postimg.org/pe2m17f3l/firefox_2017_01_20_14_27_55.jpg

Regards,

**Comment by benbasson** [comment]
Will be fixed by #24
