### ISSUE TITLE
imagetoolbar does not work with Firefox 57.0

### ISSUE THREAD

**Issue by allcoolusernamesaretakenn** [benbasson/imagetoolbar#30]

**Comment by Shaahrouz** [comment]
Will we have a new version of image toolbar for new FF or not?
It was a very useful and handy  add-on that I need it and it doesn't work since last update of FF.
Shame on Mozilla.

**Comment by franciscoluiz** [comment]
The author has already said he will not work on the new version. Another person needs to do that.

**Comment by Shaahrouz** [comment]
Where did the author say that??? I haven't seen.
I don't know nothing about writing Add-ons but if i did know i surely would do something about this add-on because i know how this add one is useful and handy and now the lack of it is so hard to work with sites like pintrest or tumblr. 

PLEASE, SOMEONE DOES SOMETHING, PLEASE.

**Comment by franciscoluiz** [comment]
Here: #24 

> I'll be honest, I have not had a lot of time to work on it, so the chances of me being finished by tomorrow (or any time in the next two weeks) are basically zero. Some of the functionality is done, e.g. save button works, the toolbar appears where it is supposed to. There's currently no proper styling. I haven't audited the security. Copy does not yet work. Print/print preview I expect to have working, but haven't started. Preferences aren't implemented. There will be no info button. Folder button is possible but not fully implemented. So, I have made progress, but probably not even 50% of the way through if I'm honest. If you really need this add-on I suggest using the Firefox 52 ESR for the time being. I will post back when I've got more to add.


And after:

> After this whole debacle, I am not even sure if I plan to ever really use or contribute to Firefox again. I am already ditching 3 of my 6 add-ons, and one of those remaining is on permanent hold until Mozilla cough up some more APIs (that I, and others, asked for over a year ago). The other two, including this one, are going to be limited in functionality because the APIs provided are, frankly, fairly rubbish.

**Comment by franciscoluiz** [comment]
imagetoolbar, is the extension that i use most in my daily life...

I just did not migrate to the new firefox quantum, just because of 2 extensions, and imagetoolbar is one of them...

**Comment by Shaahrouz** [comment]
I appreciate the author and I'm so thankful for all of these years.
But I'm mad at Mozilla because of this ridiculous changes and I bet the Firefox will lose many of it's users, at least in a short term.
And now I need an add-on that only could save an image to a folder just by one click, (like save button), do you know any?

**Comment by franciscoluiz** [comment]
I agree with you. I also need this extension.

**Comment by allcoolusernamesaretakenn** [comment]
Closest thing i found is Save image to Downloads https://addons.mozilla.org/en-US/firefox/addon/save-image-2-downloads/

**Comment by Shaahrouz** [comment]
And I've found these 
You can customize them in their setting panel and make them like Save image add-on.

1) https://addons.mozilla.org/en-US/firefox/addon/double-click-image-download/?src=userprofile

2)https://addons.mozilla.org/en-US/firefox/addon/image-picka/

**Comment by allcoolusernamesaretakenn** [comment]
I guess i should have searched with more fury and determination^^ These work. Thank you:)

**Comment by benbasson** [comment]
Uh, I am still planning to provide an update, but frankly my motivation levels are quite low, I barely if ever use Firefox now, and it's December and my free time is non-existent. Maybe I'll pick this up again in the new year.

Please track progress in #24
