### ISSUE TITLE
Suggestion : an addon like imagetoolbar but for all links

### ISSUE THREAD

**Issue by Ginko-Aloe** [benbasson/imagetoolbar#6]
Hi,

imagetoolbar is a really great addon, thank you a lot!

I've been looking for an addon that would behave just like imagetoolbar (save function) but for all links:
on link hovering, display a little button (or bar if you want to put several buttons) that opens the "save as" dialog.

If someone knows an addon that does it, let me know.

I know here is not exactly the good place to make this suggestion but i couldn't find a better since it's really imagetoolbar that inspired me.

**Comment by benbasson** [comment]
Sorry, this page isn't here for requests and I'm not in the market for writing new add-ons.
