### ISSUE TITLE
Compatibility issues with Pale Moon

### ISSUE THREAD

**Issue by Miletos02** [benbasson/imagetoolbar#9]
I'm using Pale Moon x64, which is based on Firefox. Since their latest version (25.2.0) images called from img tags are not rendered, when Image Toolbar 0.6.14 is installed. The add-on worked fine with Pale Moon 25.1.0. Newer versions of the add-on are not installable (incompatible "Firefox" version).

Pale Moon's main dev [pointed me](http://forum.palemoon.org/viewtopic.php?f=16&t=7078) to [these changes](http://forum.palemoon.org/viewtopic.php?f=46&t=7005) as the possible cause / solution. Is there anything you could do to fix the incompatibility? I've been happily using your add-on for some years.

**Comment by z235** [comment]
Another Pale Moon user here.

Hello Ben, adding support for PM would be great indeed. You seem like a cool guy, so I hope you are willing to make this compatible to our little browser project... :beers:

**Comment by gdighton** [comment]
Also a Pale Moon user, and experienced the same problem (glad to see I'm not the only one!)

**Comment by emicom** [comment]
The same with me. I've use Image Toolbar for years now and (honestly) is my favorite add-on. But with PM 25.2 is not possible to to install IT 0.6.16 or 0.6.15.
Pls Ben, can you help and make IT for PM users work? :)

**Comment by emicom** [comment]
Yeah, I think I found a solution. In the  file {A4732521-77D9-447E-A557-B279AC923F06}.xpi (it is IT xpi located in *\Application Data\Moonchild Productions\Pale Moon\Profiles\*) chrome\imagetoolbar\content\imagetoolbar.xml on entry " binding id" (I am talking for ver. 0.6.15) must be <binding id="imagetoolbar" bindToUntrustedContent="true">  - it happen twice. Then (for compatible issue of PM) in the xpi install.rdf the must change the old entry to:
<em:minVersion>25.0</em:minVersion>
<em:maxVersion>27.0.*</em:maxVersion>
Hope it temporarily helps.
Ben, can you please make IT compatible with Pale Moon 25+?:)

**Comment by Trapperman** [comment]
^^^ Ditto on everything above x100

I've become so dependent on Image Toolbar that I feel lost without it now. PLEASE Ben, make it compatible with Pale Moon v25.2++

**Comment by masoko182** [comment]
I'm another Pale Moon user, please update your awesome extension so it can be compatible. Thanks in advance!

**Comment by sobcz** [comment]
You can get my fixed version from http://1drv.ms/1GFlyFu, file image_toolbar-0.6.16-pmfix.xpi. I sent pull request some time ago, but it seems that author is busy. Then I kind of forgot about it (it worked here, so... ;).

Changes can be seen in pull request #10, plus there's changed name to "Image Toolbar (unofficial Pale Moon hotfix)". But don't trust me, check it yourself (hint: xpi is renamed zip).

**Comment by masoko182** [comment]
Thanx! It works like a charm

2015-03-14 19:54 GMT-03:00 Sob <notifications@github.com>:

**Comment by benbasson** [comment]
Hi everyone. Sorry, I have no plans to add support for Pale Moon (as I do not use it and do not want to download loads of Firefox / Mozilla forks to test my add-ons with), but I will keep maintaining the addon-on for use with Firefox. 

If someone wants to maintain a Pale Moon fork of Image Toolbar on GitHub I'm more than happy to work with them on that and am happy to share new code / features - I just don't want the extra testing / compatibility burden.

**Comment by mattatobin** [comment]
Greetings. What are your terms for the brand of "Image Toolbar" or should the Pale Moon Add-ons Team rebrand it.

**Comment by benbasson** [comment]
I'd be happy for it to be called "Image Toolbar for Pale Moon" or similar. Olease credit me as the original author + retain licence headers while adding anyone necessary as additional authors.

**Comment by mattatobin** [comment]
Of course we will follow the terms of the MPL.

**Comment by mattatobin** [comment]
We have successfully forked the code under the name Image Toolbox. All Pale Moon users should switch to this version located on our Add-ons site.

Mr. Basson thank you for your cooperation.

Feel free to close this issue.
